# This is a basic workflow to help you get started with Actions
name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: 3.9

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y cuda-toolkit-11.2  # Adjust based on your CUDA version
          sudo apt-get install -y libomp-dev  # Optional for parallel builds

      - name: Install Python dependencies
        run: |
          # Install numpy before torch to avoid missing numpy error
          pip install numpy
          
          # Install PyTorch with the specific version (with CUDA 11.2 support here)
          pip install torch==2.4.0+cu121  # Modify for the correct CUDA version
          
          # Install packaging, wheel, and other required libraries
          pip install packaging wheel
          
          # Install flash-attn with no build isolation
          pip install flash-attn==2.6.3 --no-build-isolation
          
          # Install the current package (from setup.py)
          pip install .
          
          # Install dev dependencies for testing
          pip install -r requirements-dev.txt
      
      # Hacky way to get package name from setup.py
      - name: Get package name
        id: get_package_name
        run: |
          setup_file="setup.py"
          pattern="name="
          project_name=$(grep -oP "(?<=${pattern}\")[^\"]+" $setup_file)
          echo "::set-output name=package_name::$project_name"
  
      - name: Run tests
        run: |
          pytest -v --cov-fail-under=60 --cov=${{ steps.get_package_name.outputs.package_name }} -l --tb=short --maxfail=1 tests/
          coverage xml
          coverage html